# Generated by Django 6.0.4 on 2026-05-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_payment_method_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('PHONE', 'Mobile Money (Phone)'), ('CARD', 'Bank Card'), ('SALARY', 'Salary Deposit'), ('LOAN', 'Loan Deposit'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
